export const isos = [
  // "Authorize.Net",
  // "Beyond Bancard",
  // "Cardworks",
  // "Celero (Finical)",
  // "First Direct Financial",
  // "GET",
  // "Humboldt",
  // "Maverick",
  // "MerchantE-Fresno",
  // "MerchantE-Synovous",
  // "Netevia",
  // "Nexio (CMS)",
  // "NMI",
  // "Nuvei",
  // "PayArc",
  // "PayScout",
  // "RAC",
  // "Salus Payments",
  // "Seamless Chex",
  // "SignaPay",
  // "Signature Payments",
  // "Talus Pay",
  // "Total-Apps",
  // "Vendara Payments (Choice)",
  // "Worldpay (Vantiv)",
  // "Merchant Industry",
  // "Quantum",

  "Aurora",
  "Card Insight",
  "CC Bill",
  "Coastal",
  "E-Fitness Today",
  "IPpay",
  "Merchant E",
  "Micamp",
  "MIcamp NMI",
  "MID Pals",
  "Midigator",
  "MidMetrics",
  "Pepper Pay",
];
